import os
import re
import sys
import logging
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s: %(message)s")

# 项目根目录加入 sys.path，以便导入 src 模块
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import streamlit as st

from src.config import (
    VERSION, AVAILABLE_SOURCES, REPORT_SECTORS,
    LLM_PROVIDERS, DEFAULT_LLM_PROVIDER, DEEP_LLM_PROVIDER,
)
from src.collector import NewsCollector
from src.analyzer import FinancialAnalyzer
from src.media_gen import MediaGenerator, VOICE_PRESETS, EDGE_VOICE_PRESETS, TTS_ENGINES
from src.history import HistoryManager
from src.visualizer import ASSET_GROUPS, create_asset_dashboard
from src.sentiment import MarketSentimentAnalyzer, SIGNAL_EMOJI, SIGNAL_LABEL, VIX_EMOJI
from src.newspaper import inline_markdown

# 基础路径
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
HISTORY_DIR = os.path.join(BASE_DIR, "history")

# ──────────────────────────── i18n 翻译系统 ────────────────────────────
I18N = {
    # 页面标题 & 通用
    "app_title": {"en": "🏦 Automated Financial Analysis System", "zh": "🏦 自动化金融分析系统"},
    "password_prompt": {"en": "🔒 Please enter access password", "zh": "🔒 请输入访问密码"},
    "wrong_password": {"en": "Wrong password.", "zh": "密码错误。"},

    # 侧边栏
    "sidebar_controls": {"en": "⚙️ Controls", "zh": "⚙️ 控制面板"},
    "search_query": {"en": "Search Query", "zh": "搜索关键词"},
    "search_query_default": {"en": "latest financial news market trends", "zh": "最新金融市场动态"},
    "news_sources": {"en": "News Sources", "zh": "新闻来源"},
    "time_range": {"en": "Time Range", "zh": "时间范围"},
    "num_articles": {"en": "Number of Articles", "zh": "文章数量"},
    "briefing_length": {"en": "Briefing Length", "zh": "简报长度"},
    "output_language": {"en": "Output Language / 输出语言", "zh": "Output Language / 输出语言"},
    "report_sectors": {"en": "📂 Report Sectors", "zh": "📂 报告板块"},
    "organize_sectors": {"en": "Organize by Sectors (optional)", "zh": "按板块分类组织（可选）"},
    "organize_sectors_help": {
        "en": "Reports will be organized by selected sectors; leave empty for default format",
        "zh": "选择后报告将按板块分类组织；不选则使用默认格式",
    },
    "audio_export": {"en": "🔊 Audio & Export", "zh": "🔊 音频 & 导出"},
    "generate_audio": {"en": "Generate Audio", "zh": "生成音频"},
    "tts_engine": {"en": "TTS Engine", "zh": "TTS 引擎"},
    "tts_engine_help": {
        "en": "Edge TTS is free and recommended for Chinese",
        "zh": "中文推荐使用 Edge TTS，免费且语音自然",
    },
    "voice": {"en": "Voice", "zh": "语音"},
    "export_pdf": {"en": "Export PDF", "zh": "导出 PDF"},
    "deep_analysis": {"en": "🔬 Deep Analysis", "zh": "🔬 深度分析"},
    "enable_deep": {"en": "Enable Deep Analysis", "zh": "开启深度分析"},
    "enable_deep_help": {
        "en": "Enables: 1) Full article scraping 2) Real-time market data 3) Deep analysis mode 4) Previous report comparison. Takes longer but significantly deeper.",
        "zh": "开启后将：1) 抓取文章全文 2) 注入实时市场数据 3) 深度分析模式 4) 对比上期报告。耗时更长但深度显著提升。",
    },
    "ai_search": {"en": "🔍 AI Web Search (Gemini)", "zh": "🔍 AI 联网搜索 (Gemini)"},
    "ai_search_help": {
        "en": "Use Gemini Search Grounding to find the latest news online, combined with RSS feeds",
        "zh": "使用 Gemini 联网搜索获取最新新闻，与 RSS 结果合并",
    },
    "scrape_articles": {"en": "Scrape Full Articles", "zh": "抓取文章全文"},
    "scrape_articles_help": {
        "en": "Scrape original article content for richer analysis context",
        "zh": "抓取新闻原文正文，为分析提供更丰富的上下文",
    },
    "newspaper_mode": {"en": "📰 Newspaper Layout", "zh": "📰 报纸版面"},
    "newspaper_mode_help": {
        "en": "Present the analysis report in a classic newspaper layout style",
        "zh": "将分析报告以经典报纸版面风格呈现",
    },
    "newspaper_masthead": {"en": "THE FINANCIAL TIMES BRIEFING", "zh": "金融时报简报"},
    "newspaper_edition": {"en": "Daily Intelligence Edition", "zh": "每日情报版"},
    "newspaper_disclaimer": {
        "en": "This briefing is auto-generated by AI for informational purposes only. Not financial advice. Past performance is not indicative of future results.",
        "zh": "本简报由 AI 自动生成，仅供参考。不构成投资建议。过去的表现不代表未来的结果。",
    },
    "llm_engine": {"en": "🤖 LLM Engine", "zh": "🤖 LLM 引擎"},
    "llm_provider": {"en": "Analysis Engine", "zh": "分析引擎"},
    "llm_provider_help": {
        "en": "Gemini 2.5 Flash (default) — fast, high quality, free tier available",
        "zh": "Gemini 2.5 Flash（默认）— 快速、高质量、免费额度可用",
    },
    "gemini_model": {"en": "Gemini Model", "zh": "Gemini 模型"},
    "gemini_model_help": {
        "en": "Override the default Gemini model. Can also be set via GEMINI_MODEL env var.",
        "zh": "覆盖默认 Gemini 模型。也可通过环境变量 GEMINI_MODEL 设置。",
    },
    "run_analysis": {"en": "🚀 Run Analysis", "zh": "🚀 开始分析"},
    "update_log": {"en": "📋 Update Log", "zh": "📋 更新日志"},

    # 时间范围选项
    "time_24h": {"en": "Past 24 Hours", "zh": "过去 24 小时"},
    "time_week": {"en": "Past Week", "zh": "过去一周"},
    "time_month": {"en": "Past Month", "zh": "过去一月"},

    # 简报长度选项
    "length_short": {"en": "Short (~200 words)", "zh": "简短（~200 词）"},
    "length_medium": {"en": "Medium (~400 words)", "zh": "中等（~400 词）"},
    "length_detailed": {"en": "Detailed (~800 words)", "zh": "详细（~800 词）"},

    # 标签页
    "tab_analysis": {"en": "📊 Analysis", "zh": "📊 分析"},
    "tab_sentiment": {"en": "🧭 Market Sentiment", "zh": "🧭 市场情绪"},
    "tab_charts": {"en": "📈 Market Charts", "zh": "📈 行情图表"},
    "tab_history": {"en": "📜 History", "zh": "📜 历史记录"},

    # Analysis Tab
    "collecting_news": {"en": "Collecting news...", "zh": "正在采集新闻…"},
    "no_news": {"en": "No news articles found. Try a different query.", "zh": "未找到新闻，请尝试其他关键词。"},
    "scraping_content": {"en": "Scraping full article content...", "zh": "正在抓取文章全文…"},
    "scraped_count": {"en": "📄 Scraped full content for {scraped}/{total} articles", "zh": "📄 已抓取 {scraped}/{total} 篇文章全文"},
    "collected_news": {"en": "📰 Collected News ({count} articles)", "zh": "📰 已采集新闻（{count} 篇）"},
    "chars_scraped": {"en": "{n} chars of full content scraped", "zh": "已抓取 {n} 字全文"},
    "analysis_report": {"en": "📝 Analysis Report", "zh": "📝 分析报告"},
    "audio_briefing": {"en": "🔊 Audio Briefing", "zh": "🔊 音频简报"},
    "generating_audio": {"en": "Generating audio...", "zh": "正在生成音频…"},
    "pdf_briefing": {"en": "📄 PDF Briefing", "zh": "📄 PDF 简报"},
    "generating_pdf": {"en": "Generating PDF...", "zh": "正在生成 PDF…"},
    "download_pdf": {"en": "⬇️ Download PDF", "zh": "⬇️ 下载 PDF"},
    "saving_history": {"en": "Saving to history...", "zh": "正在保存历史记录…"},
    "analysis_complete": {"en": "✅ Analysis complete! Run saved as **{run_id}**", "zh": "✅ 分析完成！已保存为 **{run_id}**"},
    "error_occurred": {"en": "An error occurred: {e}", "zh": "发生错误：{e}"},
    "cached_result": {"en": "Showing cached result from run **{run_id}**", "zh": "显示上次运行 **{run_id}** 的缓存结果"},

    # Sentiment Tab
    "sentiment_title": {"en": "🧭 Market Sentiment Dashboard", "zh": "🧭 市场情绪仪表盘"},
    "sentiment_caption": {
        "en": "Real-time multi-factor sentiment analysis across global asset classes. Data refreshes every 5 minutes.",
        "zh": "全球资产多因子实时情绪分析。数据每 5 分钟自动刷新。",
    },
    "analyzing_sentiment": {"en": "Analyzing market sentiment...", "zh": "正在分析市场情绪…"},
    "sentiment_unavailable": {"en": "Unable to fetch market data. Please try again later.", "zh": "无法获取市场数据，请稍后重试。"},
    "overall_sentiment": {"en": "Overall Sentiment", "zh": "整体情绪"},
    "bullish": {"en": "🟢 Bullish", "zh": "🟢 看多"},
    "bearish": {"en": "🔴 Bearish", "zh": "🔴 看空"},
    "bull_label": {"en": "Bull", "zh": "多"},
    "neutral_label": {"en": "Neutral", "zh": "中性"},
    "bear_label": {"en": "Bear", "zh": "空"},
    "opportunities": {"en": "### 💰 Opportunities", "zh": "### 💰 机会"},
    "no_opportunities": {"en": "No clear opportunities detected at this time.", "zh": "当前未检测到明显机会。"},
    "risks_title": {"en": "### ⚠️ Risks", "zh": "### ⚠️ 风险"},
    "no_risks": {"en": "No significant risks detected at this time.", "zh": "当前未检测到重大风险。"},
    "sector_breakdown": {"en": "📋 Sector Breakdown", "zh": "📋 板块详情"},
    "col_signal": {"en": "Signal", "zh": "信号"},
    "col_asset": {"en": "Asset", "zh": "资产"},
    "col_price": {"en": "Price", "zh": "价格"},
    "col_ma20": {"en": "MA20", "zh": "20日均线"},
    "col_above": {"en": "Above ✅", "zh": "上方 ✅"},
    "col_below": {"en": "Below ❌", "zh": "下方 ❌"},
    "col_vol_ratio": {"en": "Vol Ratio", "zh": "量比"},
    "col_score": {"en": "Score", "zh": "评分"},
    "col_reason": {"en": "Reason", "zh": "依据"},

    # Charts Tab
    "charts_title": {"en": "📈 Asset Price Trends", "zh": "📈 资产价格走势"},
    "charts_caption": {
        "en": "Select asset groups and time range to view price movements (normalized as % change).",
        "zh": "选择资产类别和时间范围查看价格走势（归一化百分比变化）。",
    },
    "asset_groups": {"en": "Asset Groups", "zh": "资产类别"},
    "period": {"en": "Period", "zh": "时间段"},
    "loading_market": {"en": "Loading market data...", "zh": "正在加载行情数据…"},
    "select_group": {"en": "Please select at least one asset group.", "zh": "请至少选择一个资产类别。"},

    # Charts period options
    "period_1w": {"en": "1 Week", "zh": "1 周"},
    "period_1m": {"en": "1 Month", "zh": "1 个月"},
    "period_3m": {"en": "3 Months", "zh": "3 个月"},
    "period_6m": {"en": "6 Months", "zh": "6 个月"},
    "period_1y": {"en": "1 Year", "zh": "1 年"},

    # History Tab
    "search_keyword": {"en": "🔍 Search keyword", "zh": "🔍 搜索关键词"},
    "search_placeholder": {"en": "Search in query or report...", "zh": "搜索查询或报告内容…"},
    "date_from": {"en": "From", "zh": "起始日期"},
    "date_to": {"en": "To", "zh": "结束日期"},
    "found_records": {"en": "Found {n} matching records", "zh": "找到 {n} 条匹配记录"},
    "no_history": {"en": "No history yet. Run an analysis to get started!", "zh": "暂无历史记录。运行一次分析即可开始！"},
    "view_details": {"en": "View details", "zh": "查看详情"},
    "no_report": {"en": "*No report available*", "zh": "*无报告*"},
    "load_failed": {"en": "Could not load run details.", "zh": "无法加载运行详情。"},
    "error_history": {"en": "Error loading history: {e}", "zh": "加载历史记录出错：{e}"},
    "no_changelog": {"en": "No changelog found.", "zh": "未找到更新日志。"},

    # 通用标签
    "query_label": {"en": "Query", "zh": "查询"},
    "sources_label": {"en": "Sources", "zh": "来源"},
    "articles_label": {"en": "Articles", "zh": "文章数"},
    "delete": {"en": "🗑️ Delete", "zh": "🗑️ 删除"},
}


def t(key, **kwargs):
    """获取当前语言的翻译文本。"""
    lang = st.session_state.get("language", "en")
    text = I18N.get(key, {}).get(lang, I18N.get(key, {}).get("en", key))
    if kwargs:
        text = text.format(**kwargs)
    return text


def sig_label(signal_key):
    """获取信号的多语言标签。"""
    lang = st.session_state.get("language", "en")
    return SIGNAL_LABEL.get(lang, SIGNAL_LABEL["en"]).get(signal_key, signal_key)


def vix_label(level_key):
    """获取 VIX 等级的多语言标签。"""
    lang = st.session_state.get("language", "en")
    return VIX_EMOJI.get(lang, VIX_EMOJI["en"]).get(level_key, level_key)


# ──────────────────────────── 页面配置 ────────────────────────────
st.set_page_config(
    page_title="Financial Analysis System / 金融分析系统",
    page_icon="🏦",
    layout="wide",
)

# ──────────────────────────── 自定义 CSS ────────────────────────────
st.markdown("""
<style>
/* ── 全局字体 & 平滑 ── */
html, body, [class*="st-"] {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans SC", sans-serif;
}

/* ── 侧边栏美化 ── */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #0f1724 0%, #1a2332 100%);
}
section[data-testid="stSidebar"] .stMarkdown p,
section[data-testid="stSidebar"] label {
    color: #c8d6e5 !important;
}

/* ── Metric 卡片 ── */
div[data-testid="stMetric"] {
    background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
    border: 1px solid #334155;
    border-radius: 12px;
    padding: 16px 20px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.2);
}
div[data-testid="stMetric"] label {
    color: #94a3b8 !important;
    font-size: 13px !important;
    font-weight: 500 !important;
}
div[data-testid="stMetric"] div[data-testid="stMetricValue"] {
    font-size: 22px !important;
    font-weight: 700 !important;
}

/* ── Tab 样式 ── */
button[data-baseweb="tab"] {
    font-size: 15px !important;
    font-weight: 600 !important;
    padding: 10px 20px !important;
}

/* ── Expander 美化 ── */
details[data-testid="stExpander"] {
    border: 1px solid #334155 !important;
    border-radius: 10px !important;
    margin-bottom: 8px;
}

/* ── 按钮美化 ── */
.stButton > button[kind="primary"],
section[data-testid="stSidebar"] .stButton > button {
    border-radius: 8px;
    font-weight: 600;
    transition: all 0.2s ease;
}
section[data-testid="stSidebar"] .stButton > button:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(59,130,246,0.3);
}

/* ── 资产卡片 ── */
.asset-card {
    background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
    border: 1px solid #334155;
    border-radius: 10px;
    padding: 14px 18px;
    margin-bottom: 10px;
    transition: border-color 0.2s ease;
}
.asset-card:hover {
    border-color: #60a5fa;
}
.asset-card .asset-name {
    font-weight: 700;
    font-size: 15px;
    margin-bottom: 4px;
}
.asset-card .asset-meta {
    color: #94a3b8;
    font-size: 13px;
    line-height: 1.6;
}
.asset-card .asset-reason {
    color: #64748b;
    font-size: 12px;
    font-style: italic;
    margin-top: 4px;
}
.positive { color: #22c55e; }
.negative { color: #ef4444; }

/* ── 情绪条 ── */
.sentiment-bar {
    display: flex;
    height: 32px;
    border-radius: 8px;
    overflow: hidden;
    margin: 12px 0 24px 0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
}
.sentiment-bar > div {
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 13px;
    font-weight: 600;
    min-width: 50px;
}

/* ── 分隔线 ── */
hr {
    border-color: #1e293b !important;
}

/* ── 数据表格 ── */
.stDataFrame {
    border-radius: 8px;
    overflow: hidden;
}

/* ═══════════════ 报纸版面 ═══════════════ */
.newspaper {
    background: #fdf6e3;
    color: #1a1a1a;
    font-family: "Georgia", "Noto Serif SC", "Source Han Serif SC", "SimSun", serif;
    padding: 40px 48px;
    border: 2px solid #8b7355;
    border-radius: 4px;
    box-shadow: 4px 4px 20px rgba(0,0,0,0.25);
    max-width: 1100px;
    margin: 20px auto;
}
@media (max-width: 768px) {
    .newspaper { padding: 20px 16px; }
    .np-columns { column-count: 1 !important; }
    .np-masthead-title { font-size: 24px !important; letter-spacing: 2px !important; }
    .np-headline { font-size: 22px !important; }
}

/* 报头 */
.np-masthead {
    text-align: center;
    border-bottom: 4px double #1a1a1a;
    padding-bottom: 12px;
    margin-bottom: 4px;
}
.np-masthead-title {
    font-size: 36px;
    font-weight: 900;
    letter-spacing: 5px;
    text-transform: uppercase;
    color: #1a1a1a;
    margin: 0;
    line-height: 1.1;
    font-family: "Times New Roman", "Noto Serif SC", serif;
}
.np-masthead-sub {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid #1a1a1a;
    border-bottom: 1px solid #1a1a1a;
    padding: 5px 0;
    margin-top: 6px;
    font-size: 11px;
    color: #555;
    letter-spacing: 1px;
}

/* 头条 */
.np-headline {
    font-size: 28px;
    font-weight: 900;
    line-height: 1.2;
    text-align: center;
    margin: 20px 0 6px 0;
    color: #1a1a1a;
    font-family: "Times New Roman", "Noto Serif SC", serif;
}
.np-subheadline {
    text-align: center;
    font-size: 15px;
    font-style: italic;
    color: #555;
    margin-bottom: 18px;
    padding-bottom: 14px;
    border-bottom: 1px solid #ccc;
}

/* 多栏布局 */
.np-columns {
    column-count: 2;
    column-gap: 36px;
    column-rule: 1px solid #ccc;
    text-align: justify;
    hyphens: auto;
}

/* 文章区块 */
.np-section {
    break-inside: avoid-column;
    -webkit-column-break-inside: avoid;
    display: inline-block;
    width: 100%;
    margin-bottom: 20px;
}
.np-section-title {
    font-size: 17px;
    font-weight: 800;
    border-bottom: 2px solid #1a1a1a;
    padding-bottom: 4px;
    margin-bottom: 8px;
    color: #1a1a1a;
    font-family: "Times New Roman", "Noto Serif SC", serif;
}
.np-body {
    font-size: 14px;
    line-height: 1.75;
    color: #2a2a2a;
}
.np-body p {
    text-indent: 2em;
    margin: 0 0 8px 0;
}
.np-body ul, .np-body ol {
    text-indent: 0;
    padding-left: 1.5em;
    margin: 6px 0 10px 0;
}
.np-body li {
    margin-bottom: 4px;
}
.np-body h3 {
    font-size: 15px;
    font-weight: 800;
    color: #1a1a1a;
    margin: 14px 0 6px 0;
    font-family: "Times New Roman", "Noto Serif SC", serif;
    border-left: 3px solid #8b7355;
    padding-left: 8px;
}

/* 引用框 */
.np-pullquote {
    break-inside: avoid;
    border-left: 4px solid #8b7355;
    border-right: 4px solid #8b7355;
    padding: 14px 18px;
    margin: 16px 0;
    font-size: 15px;
    font-style: italic;
    color: #333;
    text-align: center;
    background: rgba(139,115,85,0.06);
    line-height: 1.5;
}

/* 分隔符 */
.np-divider {
    border: none;
    border-top: 1px solid #ccc;
    margin: 16px 0;
}
.np-heavy-divider {
    border: none;
    border-top: 3px double #1a1a1a;
    margin: 20px 0;
}

/* 页脚 */
.np-footer {
    border-top: 2px solid #1a1a1a;
    margin-top: 24px;
    padding-top: 10px;
    text-align: center;
    font-size: 10px;
    color: #888;
    letter-spacing: 0.5px;
}
</style>
""", unsafe_allow_html=True)

# ──────────────────────────── 语言选择（最先加载） ────────────────────────────
# 先初始化语言（在侧边栏最顶部放置语言切换）
if "language" not in st.session_state:
    st.session_state["language"] = "en"

_lang_label = st.sidebar.selectbox(
    "🌐 Language / 语言",
    options=["English", "中文"],
    index=0 if st.session_state["language"] == "en" else 1,
    key="_lang_select",
)
_selected_lang = "zh" if _lang_label == "中文" else "en"
if _selected_lang != st.session_state["language"]:
    st.session_state["language"] = _selected_lang
    st.rerun()

language = st.session_state["language"]

st.sidebar.divider()

# ──────────────────────────── 访问密码 ────────────────────────────
ACCESS_PASSWORD = os.getenv("ACCESS_PASSWORD", "")

if ACCESS_PASSWORD:
    if "authenticated" not in st.session_state:
        st.session_state["authenticated"] = False

    if not st.session_state["authenticated"]:
        st.title(t("app_title"))
        pwd = st.text_input(t("password_prompt"), type="password")
        if pwd:
            if pwd == ACCESS_PASSWORD:
                st.session_state["authenticated"] = True
                st.rerun()
            else:
                st.error(t("wrong_password"))
        st.stop()

st.title(t("app_title"))
st.caption(f"Version {VERSION}")

# ──────────────────────────── 侧边栏 ────────────────────────────
st.sidebar.header(t("sidebar_controls"))

# LLM 引擎选择
st.sidebar.subheader(t("llm_engine"))

_llm_options = {cfg["name"]: key for key, cfg in LLM_PROVIDERS.items()}
_llm_default_name = LLM_PROVIDERS[DEFAULT_LLM_PROVIDER]["name"]
_llm_selected_name = st.sidebar.selectbox(
    t("llm_provider"),
    options=list(_llm_options.keys()),
    index=list(_llm_options.keys()).index(_llm_default_name),
    help=t("llm_provider_help"),
)
llm_provider = _llm_options[_llm_selected_name]

# Gemini 模型自定义
_gemini_model_choices = [
    "gemini-2.5-flash-preview-04-17",
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
    "gemini-1.5-pro",
    "gemini-1.5-flash",
]
_default_gemini_model = os.getenv("GEMINI_MODEL", _gemini_model_choices[0])
_gemini_model_idx = _gemini_model_choices.index(_default_gemini_model) if _default_gemini_model in _gemini_model_choices else 0
_selected_gemini_model = st.sidebar.selectbox(
    t("gemini_model"),
    options=_gemini_model_choices,
    index=_gemini_model_idx,
    help=t("gemini_model_help"),
)
os.environ["GEMINI_MODEL"] = _selected_gemini_model

st.sidebar.divider()

query = st.sidebar.text_input(
    t("search_query"),
    value=t("search_query_default"),
)

sources = st.sidebar.multiselect(
    t("news_sources"),
    options=AVAILABLE_SOURCES,
    default=AVAILABLE_SOURCES,
)

TIME_RANGE_OPTIONS = {
    t("time_24h"): "24h",
    t("time_week"): "week",
    t("time_month"): "month",
}
time_range_label = st.sidebar.selectbox(
    t("time_range"),
    options=list(TIME_RANGE_OPTIONS.keys()),
)
time_range = TIME_RANGE_OPTIONS[time_range_label]

num_articles = st.sidebar.slider(
    t("num_articles"),
    min_value=1,
    max_value=20,
    value=5,
)

BRIEFING_LENGTH_OPTIONS = {
    t("length_short"): "short",
    t("length_medium"): "medium",
    t("length_detailed"): "detailed",
}
briefing_label = st.sidebar.selectbox(
    t("briefing_length"),
    options=list(BRIEFING_LENGTH_OPTIONS.keys()),
)
briefing_length = BRIEFING_LENGTH_OPTIONS[briefing_label]

# 板块选择
st.sidebar.divider()
st.sidebar.subheader(t("report_sectors"))
selected_sectors = st.sidebar.multiselect(
    t("organize_sectors"),
    options=list(REPORT_SECTORS.keys()),
    help=t("organize_sectors_help"),
)
sector_values = [REPORT_SECTORS[s] for s in selected_sectors] if selected_sectors else None

# 语音设置
st.sidebar.divider()
st.sidebar.subheader(t("audio_export"))

generate_audio = st.sidebar.checkbox(t("generate_audio"), value=True)

tts_engine_label = st.sidebar.selectbox(
    t("tts_engine"),
    options=list(TTS_ENGINES.keys()),
    index=1 if language == "zh" else 0,
    disabled=not generate_audio,
    help=t("tts_engine_help"),
)
tts_engine = TTS_ENGINES[tts_engine_label]

# 根据引擎选择语音列表
if tts_engine == "edge_tts":
    voice_options = list(EDGE_VOICE_PRESETS.get(language, EDGE_VOICE_PRESETS["en"]).keys())
else:
    voice_options = list(VOICE_PRESETS.get(language, VOICE_PRESETS["en"]).keys())
voice_name = st.sidebar.selectbox(
    t("voice"),
    options=voice_options,
    disabled=not generate_audio,
)

generate_pdf = st.sidebar.checkbox(t("export_pdf"), value=True)

# 深度分析设置
st.sidebar.divider()
st.sidebar.subheader(t("deep_analysis"))
deep_analysis = st.sidebar.checkbox(
    t("enable_deep"),
    value=True,
    help=t("enable_deep_help"),
)
ai_search = st.sidebar.checkbox(
    t("ai_search"),
    value=True,
    disabled=not deep_analysis,
    help=t("ai_search_help"),
)
scrape_content = st.sidebar.checkbox(
    t("scrape_articles"),
    value=True,
    disabled=not deep_analysis,
    help=t("scrape_articles_help"),
)
newspaper_mode = st.sidebar.checkbox(
    t("newspaper_mode"),
    value=False,
    disabled=not deep_analysis,
    help=t("newspaper_mode_help"),
)

run_clicked = st.sidebar.button(t("run_analysis"), use_container_width=True, type="primary")

# 更新日志弹窗
st.sidebar.divider()

@st.dialog(t("update_log"), width="large")
def _show_changelog():
    _changelog_path = os.path.join(BASE_DIR, "CHANGELOG.md")
    if os.path.exists(_changelog_path):
        with open(_changelog_path, "r", encoding="utf-8") as _f:
            st.markdown(_f.read())
    else:
        st.info(t("no_changelog"))

if st.sidebar.button(t("update_log"), use_container_width=True):
    _show_changelog()

# ──────────────────────────── 公共展示函数 ────────────────────────────
def display_result(news_items, report, audio_path=None, pdf_path=None, use_newspaper=False):
    """统一展示分析结果。"""
    with st.expander(t("collected_news", count=len(news_items)), expanded=False):
        for item in news_items:
            st.markdown(
                f"**{item.get('title', 'No Title')}** "
                f"— *{item.get('source', 'Unknown')}*"
            )
            st.caption(item.get("description", ""))
            st.divider()

    st.subheader(t("analysis_report"))
    if use_newspaper:
        st.markdown(render_newspaper(report), unsafe_allow_html=True)
    else:
        st.markdown(report)

    if audio_path and os.path.exists(audio_path):
        st.subheader(t("audio_briefing"))
        st.audio(audio_path)

    if pdf_path and os.path.exists(pdf_path):
        st.subheader(t("pdf_briefing"))
        with open(pdf_path, "rb") as f:
            st.download_button(
                label=t("download_pdf"),
                data=f,
                file_name="daily_briefing.pdf",
                mime="application/pdf",
            )


# ──────────────────────────── 缓存函数 ────────────────────────────
@st.cache_data(ttl=300, show_spinner=False)
def cached_asset_dashboard(groups_tuple, period):
    return create_asset_dashboard(list(groups_tuple), period=period)


@st.cache_data(ttl=300, show_spinner=False)
def cached_sentiment():
    return MarketSentimentAnalyzer.analyze()


# ──────────────────────────── 资产卡片渲染 ────────────────────────────
def render_asset_card(a):
    """将 AssetSignal 渲染为美化的卡片 HTML。"""
    emoji = SIGNAL_EMOJI.get(a.signal, "⚪")
    label = sig_label(a.signal)
    day_cls = "positive" if a.change_1d_pct >= 0 else "negative"
    week_cls = "positive" if a.change_5d_pct >= 0 else "negative"
    return (
        f'<div class="asset-card">'
        f'<div class="asset-name">{emoji} {a.name} — {label} <span style="float:right;font-size:14px;">score <code>{a.score:+.2f}</code></span></div>'
        f'<div class="asset-meta">'
        f'{t("col_price")}: <b>{a.price:.2f}</b> &nbsp;|&nbsp; '
        f'1D: <span class="{day_cls}"><b>{a.change_1d_pct:+.1f}%</b></span> &nbsp;|&nbsp; '
        f'5D: <span class="{week_cls}"><b>{a.change_5d_pct:+.1f}%</b></span>'
        f'</div>'
        f'<div class="asset-reason">{a.reason}</div>'
        f'</div>'
    )


# ──────────────────────────── 报纸版面渲染 ────────────────────────────
def _md_to_html_body(text):
    """将 Markdown 正文段落转换为 HTML。"""
    html_parts = []
    lines = text.strip().split("\n")
    in_list = False
    list_type = None

    def _close_list():
        nonlocal in_list, list_type
        if in_list:
            html_parts.append(f"</{list_type}>")
            in_list = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            _close_list()
            continue

        # ### 子标题
        h3_match = re.match(r'^###\s+(.+)', stripped)
        if h3_match:
            _close_list()
            html_parts.append(f'<h3>{_inline_md(h3_match.group(1))}</h3>')
            continue

        # 无序列表
        if stripped.startswith(("- ", "* ")):
            if not in_list or list_type != "ul":
                _close_list()
                html_parts.append("<ul>")
                in_list = True
                list_type = "ul"
            html_parts.append(f"<li>{_inline_md(stripped[2:])}</li>")
            continue

        # 有序列表
        m = re.match(r'^(\d+)\.\s(.*)', stripped)
        if m:
            if not in_list or list_type != "ol":
                _close_list()
                html_parts.append("<ol>")
                in_list = True
                list_type = "ol"
            html_parts.append(f"<li>{_inline_md(m.group(2))}</li>")
            continue

        # 引用
        if stripped.startswith("> "):
            _close_list()
            html_parts.append(f'<div class="np-pullquote">{_inline_md(stripped[2:])}</div>')
            continue

        # 分隔线
        if stripped.startswith("---") or stripped.startswith("***"):
            _close_list()
            html_parts.append('<hr class="np-divider">')
            continue

        # 纯粗体行当作小标题（如 **Summary:** 或 **Risk Alert**）
        bold_line = re.match(r'^\*\*(.+?)\*\*[：:]*\s*$', stripped)
        if bold_line:
            _close_list()
            html_parts.append(f'<h3>{bold_line.group(1)}</h3>')
            continue

        # 普通段落
        _close_list()
        html_parts.append(f"<p>{_inline_md(stripped)}</p>")

    _close_list()
    return "\n".join(html_parts)


def _inline_md(text):
    """处理行内 Markdown 格式。"""
    return inline_markdown(text)


def _strip_emoji(text):
    """去除 Emoji 前缀，用于报纸正式排版。"""
    return re.sub(r'^[\U0001f300-\U0001fAFF\u2600-\u27BF\u2700-\u27BF]+\s*', '', text).strip()


def render_newspaper(report_md):
    """
    将 Markdown 分析报告解析为报纸版面 HTML。
    解析逻辑：
    - 第一个 ## 标题 → 头条大标题
    - 第一个 ## 下的第一句话 → 副标题
    - 后续 ## 标题 → 各版块 section
    - 正文转 HTML 段落
    """
    # 按 ## 分割为 sections（不匹配 ###）
    parts = re.split(r'^##(?!#)\s+', report_md, flags=re.MULTILINE)

    headline = ""
    subheadline = ""
    sections = []

    for i, part in enumerate(parts):
        part = part.strip()
        if not part:
            continue

        if i == 0:
            # ## 之前的内容（可能有 # 大标题）
            m = re.match(r'^#\s+(.+)', part)
            if m:
                headline = _strip_emoji(m.group(1).strip())
                rest = part[m.end():].strip()
                if rest:
                    sections.append({"title": "", "body": rest})
            elif part:
                sections.append({"title": "", "body": part})
            continue

        # 提取标题行（第一行）
        lines = part.split("\n", 1)
        section_title = _strip_emoji(lines[0].strip())
        section_body = lines[1].strip() if len(lines) > 1 else ""

        if i == 1 and not headline:
            # 第一个 ## section → headline + subheadline
            headline = section_title
            # 取正文第一句作为副标题
            first_para = section_body.split("\n\n")[0] if section_body else ""
            first_sentence = re.split(r'[.!?。！？]', first_para)
            if first_sentence and first_sentence[0].strip():
                subheadline = _inline_md(first_sentence[0].strip().lstrip("- *"))

        if section_body:
            sections.append({"title": section_title, "body": section_body})

    if not headline:
        headline = t("newspaper_masthead")

    # 构建 HTML
    now = datetime.now()
    date_str = now.strftime("%A, %B %d, %Y") if language == "en" else now.strftime("%Y年%m月%d日 %A")
    edition = t("newspaper_edition")
    vol_no = f"Vol. {now.strftime('%Y')} No. {now.strftime('%j')}"

    html = f'''<div class="newspaper">
<!-- 报头 -->
<div class="np-masthead">
    <div class="np-masthead-title">{t("newspaper_masthead")}</div>
    <div class="np-masthead-sub">
        <span>{date_str}</span>
        <span>{edition}</span>
        <span>{vol_no}</span>
    </div>
</div>

<!-- 头条 -->
<div class="np-headline">{_inline_md(headline)}</div>
'''
    if subheadline:
        html += f'<div class="np-subheadline">{subheadline}</div>\n'
    else:
        html += '<div class="np-subheadline">&nbsp;</div>\n'

    html += '<hr class="np-heavy-divider">\n'

    # 版面分布：长报告分两段双栏，短报告单段双栏
    if len(sections) >= 4:
        mid = (len(sections) + 1) // 2
        groups = [sections[:mid], sections[mid:]]
    else:
        groups = [sections]

    for gi, group in enumerate(groups):
        if gi > 0:
            html += '<hr class="np-heavy-divider">\n'
        html += '<div class="np-columns">\n'
        for sec in group:
            html += '<div class="np-section">\n'
            if sec["title"]:
                html += f'<div class="np-section-title">{_inline_md(sec["title"])}</div>\n'
            html += f'<div class="np-body">{_md_to_html_body(sec["body"])}</div>\n'
            html += '</div>\n'
        html += '</div>\n'

    # 页脚
    html += f'''
<div class="np-footer">
    {t("newspaper_disclaimer")}<br>
    &copy; {now.strftime("%Y")} Financial Analysis System {VERSION}
</div>
</div>'''

    return html


# ──────────────────────────── 主区域 ────────────────────────────
tab_analysis, tab_sentiment, tab_charts, tab_history = st.tabs([
    t("tab_analysis"), t("tab_sentiment"), t("tab_charts"), t("tab_history"),
])

# ═══════════════════ Analysis Tab ═══════════════════
with tab_analysis:
    if run_clicked:
        try:
            os.makedirs(DATA_DIR, exist_ok=True)

            # 1. 采集新闻
            with st.spinner(t("collecting_news")):
                collector = NewsCollector()
                news_items = collector.fetch_news(
                    query=query,
                    count=num_articles,
                    sources=sources,
                    time_range=time_range,
                    ai_search=deep_analysis and ai_search,
                )

            if not news_items:
                st.warning(t("no_news"))
            else:
                # 1b. 抓取全文（深度分析模式）
                if deep_analysis and scrape_content:
                    with st.spinner(t("scraping_content")):
                        collector.enrich_with_content(news_items)
                    scraped = sum(1 for it in news_items if it.get("full_content"))
                    st.caption(t("scraped_count", scraped=scraped, total=len(news_items)))

                # 展示采集结果
                with st.expander(t("collected_news", count=len(news_items)), expanded=False):
                    for item in news_items:
                        st.markdown(
                            f"**{item.get('title', 'No Title')}** "
                            f"— *{item.get('source', 'Unknown')}*"
                        )
                        desc = item.get("description", "")
                        full = item.get("full_content", "")
                        if full:
                            st.caption(f"{desc}\n\n📄 _{t('chars_scraped', n=len(full))}_")
                        else:
                            st.caption(desc)
                        st.divider()

                # 1c. 加载上期报告
                previous_report = None
                previous_report_meta = None
                hm_prev = HistoryManager(history_dir=HISTORY_DIR)
                prev_runs = hm_prev.list_runs()
                if prev_runs:
                    prev_data = hm_prev.load_run(prev_runs[0]["run_id"])
                    if prev_data and prev_data.get("report"):
                        previous_report = prev_data["report"]
                        previous_report_meta = prev_data.get("metadata")

                # 2. AI 分析
                st.subheader(t("analysis_report"))
                analyzer = FinancialAnalyzer(provider=llm_provider)

                status_placeholder = st.empty()
                def on_status(msg):
                    status_placeholder.info(msg)

                report_container = st.empty()
                report_chunks = []

                stream = analyzer.analyze_news_stream(
                    news_items,
                    briefing_length=briefing_length,
                    language=language,
                    sectors=sector_values,
                    previous_report=previous_report,
                    deep_analysis=deep_analysis,
                    on_status=on_status if deep_analysis else None,
                    time_range=time_range,
                    previous_report_meta=previous_report_meta,
                )
                for chunk in stream:
                    report_chunks.append(chunk)
                    report_container.markdown("".join(report_chunks))

                status_placeholder.empty()
                report = "".join(report_chunks)

                # 报纸版面模式：用报纸 HTML 替换流式 Markdown
                if newspaper_mode and deep_analysis:
                    report_container.empty()
                    report_container.markdown(render_newspaper(report), unsafe_allow_html=True)

                # 保存报告
                report_path = os.path.join(DATA_DIR, "daily_report.md")
                analyzer.save_analysis(report, report_path)

                audio_path = None
                pdf_path = None
                media_gen = MediaGenerator()

                # 3. 音频
                if generate_audio:
                    with st.spinner(t("generating_audio")):
                        audio_path = media_gen.generate_audio(
                            report,
                            output_file=os.path.join(DATA_DIR, "daily_briefing.mp3"),
                            language=language,
                            voice_name=voice_name,
                            tts_engine=tts_engine,
                        )
                    if audio_path and os.path.exists(audio_path):
                        st.subheader(t("audio_briefing"))
                        st.audio(audio_path)

                # 4. PDF 导出
                if generate_pdf:
                    with st.spinner(t("generating_pdf")):
                        pdf_title = "金融分析简报" if language == "zh" else "Financial Analysis Briefing"
                        pdf_path = media_gen.generate_pdf(
                            report,
                            output_file=os.path.join(DATA_DIR, "daily_briefing.pdf"),
                            language=language,
                            title=pdf_title,
                        )
                    if pdf_path and os.path.exists(pdf_path):
                        st.subheader(t("pdf_briefing"))
                        with open(pdf_path, "rb") as f:
                            st.download_button(
                                label=t("download_pdf"),
                                data=f,
                                file_name="daily_briefing.pdf",
                                mime="application/pdf",
                            )

                # 5. 保存到历史记录
                with st.spinner(t("saving_history")):
                    hm = HistoryManager(history_dir=HISTORY_DIR)
                    run_id = hm.save_run(
                        news_items=news_items,
                        report=report,
                        query=query,
                        sources=sources,
                        time_range=time_range,
                        briefing_length=briefing_length,
                        audio_file=audio_path,
                        pdf_file=pdf_path,
                    )

                st.success(t("analysis_complete", run_id=run_id))

                st.session_state["last_result"] = {
                    "news_items": news_items,
                    "report": report,
                    "audio_path": audio_path,
                    "pdf_path": pdf_path,
                    "run_id": run_id,
                    "newspaper_mode": newspaper_mode and deep_analysis,
                }

        except Exception as e:
            st.error(t("error_occurred", e=e))

    elif "last_result" in st.session_state:
        result = st.session_state["last_result"]
        st.info(t("cached_result", run_id=result["run_id"]))
        display_result(
            result["news_items"],
            result["report"],
            result.get("audio_path"),
            result.get("pdf_path"),
            use_newspaper=result.get("newspaper_mode", False),
        )

# ═══════════════════ Sentiment Tab ═══════════════════
with tab_sentiment:
    st.subheader(t("sentiment_title"))
    st.caption(t("sentiment_caption"))

    with st.spinner(t("analyzing_sentiment")):
        sentiment = cached_sentiment()

    if not sentiment.all_assets:
        st.warning(t("sentiment_unavailable"))
    else:
        # ── 顶部总览指标 ──
        overview_cols = st.columns(4)
        with overview_cols[0]:
            _sig_emoji = SIGNAL_EMOJI.get(sentiment.overall_signal, "⚪")
            _sig_label = sig_label(sentiment.overall_signal)
            st.metric(
                t("overall_sentiment"),
                f"{_sig_emoji} {_sig_label}",
                f"{sentiment.overall_score:+.2f}",
            )
        with overview_cols[1]:
            st.metric(t("bullish"), sentiment.bull_count)
        with overview_cols[2]:
            st.metric(t("bearish"), sentiment.bear_count)
        with overview_cols[3]:
            _vix_label = vix_label(sentiment.vix_level)
            st.metric("VIX", f"{sentiment.vix_value:.1f}", _vix_label)

        # ── 多空比例条 ──
        total = sentiment.bull_count + sentiment.bear_count + sentiment.neutral_count
        if total > 0:
            bull_pct = sentiment.bull_count / total * 100
            bear_pct = sentiment.bear_count / total * 100
            neutral_pct = sentiment.neutral_count / total * 100
            st.markdown(
                f'<div class="sentiment-bar">'
                f'<div style="width:{bull_pct}%; background:linear-gradient(90deg,#16a34a,#22c55e);">'
                f'{bull_pct:.0f}% {t("bull_label")}</div>'
                f'<div style="width:{neutral_pct}%; background:linear-gradient(90deg,#4b5563,#6b7280);">'
                f'{neutral_pct:.0f}% {t("neutral_label")}</div>'
                f'<div style="width:{bear_pct}%; background:linear-gradient(90deg,#ef4444,#dc2626);">'
                f'{bear_pct:.0f}% {t("bear_label")}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )

        # ── 机会 & 风险 双栏 ──
        opp_col, risk_col = st.columns(2)

        with opp_col:
            st.markdown(t("opportunities"))
            if sentiment.opportunities:
                cards_html = "".join(render_asset_card(a) for a in sentiment.opportunities)
                st.markdown(cards_html, unsafe_allow_html=True)
            else:
                st.info(t("no_opportunities"))

        with risk_col:
            st.markdown(t("risks_title"))
            if sentiment.risks:
                cards_html = "".join(render_asset_card(a) for a in sentiment.risks)
                st.markdown(cards_html, unsafe_allow_html=True)
            else:
                st.info(t("no_risks"))

        # ── 各板块详情 ──
        st.markdown("---")
        st.subheader(t("sector_breakdown"))
        for group_name, sector in sentiment.sectors.items():
            sector_emoji = SIGNAL_EMOJI.get(sector.signal, "⚪")
            sector_label_text = sig_label(sector.signal)
            with st.expander(
                f"{sector_emoji} **{group_name}** — {sector_label_text} "
                f"({t('col_score')}: {sector.avg_score:+.2f} | 🟢{sector.bull_count} ⚪{sector.neutral_count} 🔴{sector.bear_count})",
                expanded=False,
            ):
                if sector.assets:
                    rows = []
                    for a in sorted(sector.assets, key=lambda x: x.score, reverse=True):
                        rows.append({
                            t("col_signal"): f"{SIGNAL_EMOJI.get(a.signal, '⚪')} {sig_label(a.signal)}",
                            t("col_asset"): a.name,
                            t("col_price"): f"{a.price:.2f}",
                            "1D %": f"{a.change_1d_pct:+.1f}%",
                            "5D %": f"{a.change_5d_pct:+.1f}%",
                            "20D %": f"{a.change_20d_pct:+.1f}%",
                            t("col_ma20"): t("col_above") if a.above_ma20 else t("col_below"),
                            t("col_vol_ratio"): f"{a.volume_ratio:.1f}x",
                            t("col_score"): f"{a.score:+.2f}",
                            t("col_reason"): a.reason,
                        })
                    st.dataframe(rows, use_container_width=True, hide_index=True)

# ═══════════════════ Charts Tab ═══════════════════
CHART_PERIOD_OPTIONS = {
    t("period_1w"): "5d",
    t("period_1m"): "1mo",
    t("period_3m"): "3mo",
    t("period_6m"): "6mo",
    t("period_1y"): "1y",
}

with tab_charts:
    st.subheader(t("charts_title"))
    st.caption(t("charts_caption"))

    chart_col1, chart_col2 = st.columns([3, 1])
    with chart_col1:
        chart_groups = st.multiselect(
            t("asset_groups"),
            options=list(ASSET_GROUPS.keys()),
            default=list(ASSET_GROUPS.keys())[:3],
            key="chart_groups",
        )
    with chart_col2:
        chart_period_label = st.selectbox(
            t("period"),
            options=list(CHART_PERIOD_OPTIONS.keys()),
            index=1,
            key="chart_period",
        )
    chart_period = CHART_PERIOD_OPTIONS[chart_period_label]

    if chart_groups:
        with st.spinner(t("loading_market")):
            figures = cached_asset_dashboard(tuple(chart_groups), chart_period)
        for group_name, fig in figures.items():
            st.plotly_chart(fig, use_container_width=True)
    else:
        st.info(t("select_group"))

# ═══════════════════ History Tab ═══════════════════
with tab_history:
    try:
        hm = HistoryManager(history_dir=HISTORY_DIR)

        hist_col1, hist_col2, hist_col3 = st.columns([2, 1, 1])
        with hist_col1:
            hist_keyword = st.text_input(
                t("search_keyword"), key="hist_keyword",
                placeholder=t("search_placeholder"),
            )
        with hist_col2:
            hist_date_from = st.date_input(t("date_from"), value=None, key="hist_date_from")
        with hist_col3:
            hist_date_to = st.date_input(t("date_to"), value=None, key="hist_date_to")

        if hist_keyword or hist_date_from or hist_date_to:
            date_from_str = hist_date_from.isoformat() if hist_date_from else None
            date_to_str = hist_date_to.isoformat() if hist_date_to else None
            runs = hm.search_runs(keyword=hist_keyword or None, date_from=date_from_str, date_to=date_to_str)
            st.caption(t("found_records", n=len(runs)))
        else:
            runs = hm.list_runs()

        if not runs:
            st.info(t("no_history"))
        else:
            for run in runs:
                run_id = run.get("run_id", "unknown")
                col1, col2 = st.columns([5, 1])

                with col1:
                    st.markdown(
                        f"**{run.get('timestamp', 'N/A')}** — "
                        f"{t('query_label')}: *{run.get('query', '')}* — "
                        f"{t('sources_label')}: {', '.join(run.get('sources', []))} — "
                        f"{t('articles_label')}: {run.get('num_articles', 0)}"
                    )

                with col2:
                    if st.button(t("delete"), key=f"del_{run_id}"):
                        hm.delete_run(run_id)
                        st.rerun()

                with st.expander(f"{t('view_details')} — {run_id}"):
                    full_run = hm.load_run(run_id)
                    if full_run:
                        st.markdown(full_run.get("report", t("no_report")))

                        audio = full_run.get("audio_path")
                        if audio and os.path.exists(audio):
                            st.audio(audio)

                        pdf = full_run.get("pdf_path")
                        if pdf and os.path.exists(pdf):
                            with open(pdf, "rb") as f:
                                st.download_button(
                                    label=t("download_pdf"),
                                    data=f,
                                    file_name=f"briefing_{run_id}.pdf",
                                    mime="application/pdf",
                                    key=f"pdf_{run_id}",
                                )
                    else:
                        st.warning(t("load_failed"))

                st.divider()

    except Exception as e:
        st.error(t("error_history", e=e))
