"""
国际化 (i18n) 翻译系统。
所有 UI 文本集中管理，支持中英文切换。
"""

import streamlit as st

from src.sentiment import SIGNAL_LABEL, VIX_EMOJI

# ──────────────────────────── 翻译字典 ────────────────────────────
I18N = {
    # 页面标题 & 通用
    "app_title": {"en": "🏦 Automated Financial Analysis System", "zh": "🏦 自动化金融分析系统"},
    "password_prompt": {"en": "🔒 Please enter access password", "zh": "🔒 请输入访问密码"},
    "wrong_password": {"en": "Wrong password.", "zh": "密码错误。"},

    # 侧边栏
    "sidebar_controls": {"en": "⚙️ Controls", "zh": "⚙️ 控制面板"},
    "search_query": {"en": "Search Query", "zh": "搜索关键词"},
    "search_query_default": {"en": "latest financial news market trends", "zh": "最新金融市场动态"},
    "news_sources": {"en": "News Sources", "zh": "新闻来源"},
    "time_range": {"en": "Time Range", "zh": "时间范围"},
    "num_articles": {"en": "Number of Articles", "zh": "文章数量"},
    "briefing_length": {"en": "Briefing Length", "zh": "简报长度"},
    "output_language": {"en": "Output Language / 输出语言", "zh": "Output Language / 输出语言"},
    "report_sectors": {"en": "📂 Report Sectors", "zh": "📂 报告板块"},
    "organize_sectors": {"en": "Organize by Sectors (optional)", "zh": "按板块分类组织（可选）"},
    "organize_sectors_help": {
        "en": "Reports will be organized by selected sectors; leave empty for default format",
        "zh": "选择后报告将按板块分类组织；不选则使用默认格式",
    },
    "audio_export": {"en": "🔊 Audio & Export", "zh": "🔊 音频 & 导出"},
    "generate_audio": {"en": "Generate Audio", "zh": "生成音频"},
    "tts_engine": {"en": "TTS Engine", "zh": "TTS 引擎"},
    "tts_engine_help": {
        "en": "Edge TTS is free and recommended for Chinese",
        "zh": "中文推荐使用 Edge TTS，免费且语音自然",
    },
    "voice": {"en": "Voice", "zh": "语音"},
    "export_pdf": {"en": "Export PDF", "zh": "导出 PDF"},
    "deep_analysis": {"en": "🔬 Deep Analysis", "zh": "🔬 深度分析"},
    "enable_deep": {"en": "Enable Deep Analysis", "zh": "开启深度分析"},
    "enable_deep_help": {
        "en": "Enables: 1) Full article scraping 2) Real-time market data 3) Deep analysis mode 4) Previous report comparison. Takes longer but significantly deeper.",
        "zh": "开启后将：1) 抓取文章全文 2) 注入实时市场数据 3) 深度分析模式 4) 对比上期报告。耗时更长但深度显著提升。",
    },
    "ai_search": {"en": "🔍 AI Web Search (Gemini)", "zh": "🔍 AI 联网搜索 (Gemini)"},
    "ai_search_help": {
        "en": "Use Gemini Search Grounding to find the latest news online, combined with RSS feeds",
        "zh": "使用 Gemini 联网搜索获取最新新闻，与 RSS 结果合并",
    },
    "scrape_articles": {"en": "Scrape Full Articles", "zh": "抓取文章全文"},
    "scrape_articles_help": {
        "en": "Scrape original article content for richer analysis context",
        "zh": "抓取新闻原文正文，为分析提供更丰富的上下文",
    },
    "newspaper_mode": {"en": "📰 Newspaper Layout", "zh": "📰 报纸版面"},
    "newspaper_mode_help": {
        "en": "Present the analysis report in a classic newspaper layout style",
        "zh": "将分析报告以经典报纸版面风格呈现",
    },
    "newspaper_masthead": {"en": "THE FINANCIAL TIMES BRIEFING", "zh": "金融时报简报"},
    "newspaper_edition": {"en": "Daily Intelligence Edition", "zh": "每日情报版"},
    "newspaper_disclaimer": {
        "en": "This briefing is auto-generated by AI for informational purposes only. Not financial advice. Past performance is not indicative of future results.",
        "zh": "本简报由 AI 自动生成，仅供参考。不构成投资建议。过去的表现不代表未来的结果。",
    },
    "llm_engine": {"en": "🤖 LLM Engine", "zh": "🤖 LLM 引擎"},
    "llm_provider": {"en": "Analysis Engine", "zh": "分析引擎"},
    "llm_provider_help": {
        "en": "Gemini 2.5 Flash (default) — fast, high quality, free tier available",
        "zh": "Gemini 2.5 Flash（默认）— 快速、高质量、免费额度可用",
    },
    "gemini_model": {"en": "Gemini Model", "zh": "Gemini 模型"},
    "gemini_model_help": {
        "en": "Override the default Gemini model. Can also be set via GEMINI_MODEL env var.",
        "zh": "覆盖默认 Gemini 模型。也可通过环境变量 GEMINI_MODEL 设置。",
    },
    "run_analysis": {"en": "🚀 Run Analysis", "zh": "🚀 开始分析"},
    "update_log": {"en": "📋 Update Log", "zh": "📋 更新日志"},

    # 时间范围选项
    "time_24h": {"en": "Past 24 Hours", "zh": "过去 24 小时"},
    "time_week": {"en": "Past Week", "zh": "过去一周"},
    "time_month": {"en": "Past Month", "zh": "过去一月"},

    # 简报长度选项
    "length_short": {"en": "Short (~200 words)", "zh": "简短（~200 词）"},
    "length_medium": {"en": "Medium (~400 words)", "zh": "中等（~400 词）"},
    "length_detailed": {"en": "Detailed (~800 words)", "zh": "详细（~800 词）"},

    # 标签页
    "tab_analysis": {"en": "📊 Analysis", "zh": "📊 分析"},
    "tab_sentiment": {"en": "🧭 Market Sentiment", "zh": "🧭 市场情绪"},
    "tab_charts": {"en": "📈 Market Charts", "zh": "📈 行情图表"},
    "tab_history": {"en": "📜 History", "zh": "📜 历史记录"},

    # Analysis Tab
    "collecting_news": {"en": "Collecting news...", "zh": "正在采集新闻…"},
    "no_news": {"en": "No news articles found. Try a different query.", "zh": "未找到新闻，请尝试其他关键词。"},
    "scraping_content": {"en": "Scraping full article content...", "zh": "正在抓取文章全文…"},
    "scraped_count": {"en": "📄 Scraped full content for {scraped}/{total} articles", "zh": "📄 已抓取 {scraped}/{total} 篇文章全文"},
    "collected_news": {"en": "📰 Collected News ({count} articles)", "zh": "📰 已采集新闻（{count} 篇）"},
    "chars_scraped": {"en": "{n} chars of full content scraped", "zh": "已抓取 {n} 字全文"},
    "analysis_report": {"en": "📝 Analysis Report", "zh": "📝 分析报告"},
    "audio_briefing": {"en": "🔊 Audio Briefing", "zh": "🔊 音频简报"},
    "generating_audio": {"en": "Generating audio...", "zh": "正在生成音频…"},
    "pdf_briefing": {"en": "📄 PDF Briefing", "zh": "📄 PDF 简报"},
    "generating_pdf": {"en": "Generating PDF...", "zh": "正在生成 PDF…"},
    "download_pdf": {"en": "⬇️ Download PDF", "zh": "⬇️ 下载 PDF"},
    "saving_history": {"en": "Saving to history...", "zh": "正在保存历史记录…"},
    "analysis_complete": {"en": "Analysis complete! Run saved as **{run_id}**", "zh": "分析完成！已保存为 **{run_id}**"},
    "error_occurred": {"en": "An error occurred: {e}", "zh": "发生错误：{e}"},
    "cached_result": {"en": "Showing cached result from run **{run_id}**", "zh": "显示上次运行 **{run_id}** 的缓存结果"},

    # Progress steps
    "step_collect": {"en": "Step 1/5: Collecting news", "zh": "步骤 1/5：采集新闻"},
    "step_scrape": {"en": "Step 2/5: Scraping full articles", "zh": "步骤 2/5：抓取文章全文"},
    "step_analyze": {"en": "Step 3/5: AI analysis in progress", "zh": "步骤 3/5：AI 分析中"},
    "step_media": {"en": "Step 4/5: Generating media", "zh": "步骤 4/5：生成媒体文件"},
    "step_save": {"en": "Step 5/5: Saving results", "zh": "步骤 5/5：保存结果"},

    # Sidebar presets
    "preset_label": {"en": "Quick Presets", "zh": "快速预设"},
    "preset_quick": {"en": "⚡ Quick Briefing", "zh": "⚡ 快速简报"},
    "preset_deep": {"en": "🔬 Deep Report", "zh": "🔬 深度报告"},
    "preset_china": {"en": "🇨🇳 China A-Share Focus", "zh": "🇨🇳 A 股聚焦"},
    "preset_custom": {"en": "🔧 Custom", "zh": "🔧 自定义"},
    "basic_settings": {"en": "📋 Basic Settings", "zh": "📋 基础设置"},
    "advanced_settings": {"en": "🔧 Advanced Settings", "zh": "🔧 高级设置"},

    # Sentiment Tab
    "sentiment_title": {"en": "🧭 Market Sentiment Dashboard", "zh": "🧭 市场情绪仪表盘"},
    "sentiment_caption": {
        "en": "Real-time multi-factor sentiment analysis across global asset classes. Data refreshes every 5 minutes.",
        "zh": "全球资产多因子实时情绪分析。数据每 5 分钟自动刷新。",
    },
    "analyzing_sentiment": {"en": "Analyzing market sentiment...", "zh": "正在分析市场情绪…"},
    "sentiment_unavailable": {"en": "Unable to fetch market data. Please try again later.", "zh": "无法获取市场数据，请稍后重试。"},
    "overall_sentiment": {"en": "Overall Sentiment", "zh": "整体情绪"},
    "bullish": {"en": "🟢 Bullish", "zh": "🟢 看多"},
    "bearish": {"en": "🔴 Bearish", "zh": "🔴 看空"},
    "bull_label": {"en": "Bull", "zh": "多"},
    "neutral_label": {"en": "Neutral", "zh": "中性"},
    "bear_label": {"en": "Bear", "zh": "空"},
    "opportunities": {"en": "### 💰 Opportunities", "zh": "### 💰 机会"},
    "no_opportunities": {"en": "No clear opportunities detected at this time.", "zh": "当前未检测到明显机会。"},
    "risks_title": {"en": "### ⚠️ Risks", "zh": "### ⚠️ 风险"},
    "no_risks": {"en": "No significant risks detected at this time.", "zh": "当前未检测到重大风险。"},
    "sector_breakdown": {"en": "📋 Sector Breakdown", "zh": "📋 板块详情"},
    "col_signal": {"en": "Signal", "zh": "信号"},
    "col_asset": {"en": "Asset", "zh": "资产"},
    "col_price": {"en": "Price", "zh": "价格"},
    "col_ma20": {"en": "MA20", "zh": "20日均线"},
    "col_above": {"en": "Above", "zh": "上方"},
    "col_below": {"en": "Below", "zh": "下方"},
    "col_vol_ratio": {"en": "Vol Ratio", "zh": "量比"},
    "col_score": {"en": "Score", "zh": "评分"},
    "col_reason": {"en": "Reason", "zh": "依据"},
    "refresh_data": {"en": "🔄 Refresh Data", "zh": "🔄 刷新数据"},
    "last_updated": {"en": "Last updated: {time}", "zh": "上次更新：{time}"},
    "click_refresh": {"en": "Click \"Refresh Data\" to load market sentiment.", "zh": "点击「刷新数据」加载市场情绪。"},
    "click_refresh_charts": {"en": "Click \"Refresh Data\" to load market charts.", "zh": "点击「刷新数据」加载行情图表。"},

    # Charts Tab
    "charts_title": {"en": "📈 Asset Price Trends", "zh": "📈 资产价格走势"},
    "charts_caption": {
        "en": "Select asset groups and time range to view price movements (normalized as % change).",
        "zh": "选择资产类别和时间范围查看价格走势（归一化百分比变化）。",
    },
    "asset_groups": {"en": "Asset Groups", "zh": "资产类别"},
    "period": {"en": "Period", "zh": "时间段"},
    "loading_market": {"en": "Loading market data...", "zh": "正在加载行情数据…"},
    "select_group": {"en": "Please select at least one asset group.", "zh": "请至少选择一个资产类别。"},

    # Charts period options
    "period_1w": {"en": "1 Week", "zh": "1 周"},
    "period_1m": {"en": "1 Month", "zh": "1 个月"},
    "period_3m": {"en": "3 Months", "zh": "3 个月"},
    "period_6m": {"en": "6 Months", "zh": "6 个月"},
    "period_1y": {"en": "1 Year", "zh": "1 年"},

    # History Tab
    "search_keyword": {"en": "🔍 Search keyword", "zh": "🔍 搜索关键词"},
    "search_placeholder": {"en": "Search in query or report...", "zh": "搜索查询或报告内容…"},
    "date_from": {"en": "From", "zh": "起始日期"},
    "date_to": {"en": "To", "zh": "结束日期"},
    "found_records": {"en": "Found {n} matching records", "zh": "找到 {n} 条匹配记录"},
    "no_history": {"en": "No history yet. Run an analysis to get started!", "zh": "暂无历史记录。运行一次分析即可开始！"},
    "view_details": {"en": "View details", "zh": "查看详情"},
    "no_report": {"en": "*No report available*", "zh": "*无报告*"},
    "load_failed": {"en": "Could not load run details.", "zh": "无法加载运行详情。"},
    "error_history": {"en": "Error loading history: {e}", "zh": "加载历史记录出错：{e}"},
    "no_changelog": {"en": "No changelog found.", "zh": "未找到更新日志。"},
    "export_zip": {"en": "📦 Export All as ZIP", "zh": "📦 导出全部为 ZIP"},
    "export_selected": {"en": "📦 Export Selected", "zh": "📦 导出已选"},
    "compare_reports": {"en": "📊 Compare Reports", "zh": "📊 对比报告"},
    "select_compare": {"en": "Select two reports to compare", "zh": "选择两个报告进行对比"},
    "compare_left": {"en": "Report A", "zh": "报告 A"},
    "compare_right": {"en": "Report B", "zh": "报告 B"},
    "no_diff": {"en": "Reports are identical.", "zh": "两份报告内容相同。"},

    # Newspaper themes
    "newspaper_theme": {"en": "Newspaper Theme", "zh": "报纸主题"},
    "theme_classic": {"en": "📜 Classic", "zh": "📜 经典"},
    "theme_modern": {"en": "✨ Modern", "zh": "✨ 现代"},

    # Charts enhancements
    "chart_type": {"en": "Chart Type", "zh": "图表类型"},
    "chart_line": {"en": "Line Chart", "zh": "折线图"},
    "chart_candlestick": {"en": "Candlestick", "zh": "K线图"},
    "chart_correlation": {"en": "📊 Correlation Matrix", "zh": "📊 相关性矩阵"},
    "correlation_title": {"en": "Asset Correlation Matrix", "zh": "资产相关性矩阵"},
    "custom_date_range": {"en": "Custom Date Range", "zh": "自定义日期范围"},
    "date_start": {"en": "Start Date", "zh": "开始日期"},
    "date_end": {"en": "End Date", "zh": "结束日期"},

    # News display enhancements
    "news_group_by": {"en": "Group by", "zh": "分组方式"},
    "group_none": {"en": "No Grouping", "zh": "不分组"},
    "group_source": {"en": "By Source", "zh": "按来源"},
    "sentiment_positive": {"en": "🟢 Positive", "zh": "🟢 正面"},
    "sentiment_negative": {"en": "🔴 Negative", "zh": "🔴 负面"},
    "sentiment_neutral_tag": {"en": "⚪ Neutral", "zh": "⚪ 中性"},

    # 通用标签
    "query_label": {"en": "Query", "zh": "查询"},
    "sources_label": {"en": "Sources", "zh": "来源"},
    "articles_label": {"en": "Articles", "zh": "文章数"},
    "delete": {"en": "🗑️ Delete", "zh": "🗑️ 删除"},
}


def t(key, **kwargs):
    """获取当前语言的翻译文本。"""
    lang = st.session_state.get("language", "en")
    text = I18N.get(key, {}).get(lang, I18N.get(key, {}).get("en", key))
    if kwargs:
        text = text.format(**kwargs)
    return text


def sig_label(signal_key):
    """获取信号的多语言标签。"""
    lang = st.session_state.get("language", "en")
    return SIGNAL_LABEL.get(lang, SIGNAL_LABEL["en"]).get(signal_key, signal_key)


def vix_label(level_key):
    """获取 VIX 等级的多语言标签。"""
    lang = st.session_state.get("language", "en")
    return VIX_EMOJI.get(lang, VIX_EMOJI["en"]).get(level_key, level_key)
